### ISSUE TITLE
Unify tabs - revised

### ISSUE THREAD

**Issue by ujovlado** [keboola/indigo-ui#102]
Spravim to takto:

- [x] ku vsetkym tabom sa da custom classa: https://github.com/keboola/kbc-ui/pull/1517
- [x] tejto classe, ked obsahuje `.tab-pane` pridame top padding (na job detaile v orchestracii sa to resetne) #103 
- [x] release indigo-ui
- [x] potom z kbc-ui vyhodime nepotrebne classes a prerobi sa pouzitie tabs, kde je ten sprosty `.row` a na nom 20px margin keboola/kbc-ui#1519
- [x] z indigo mozeme vyhodit zbytocne styles #105
- [x] release indigo-ui
- [x] potom z kbc-ui vyhodit malu cast, co docasne resetovala `row` keboola/kbc-ui#1520
- [x] fixnut orch. job detail - pouzil som tam nove "spacing" classes kbc-ui/pull/1524

**Comment by ujovlado** [comment]
Hotovo, fixli vsetky veci, co som spominal v #84
