### ISSUE TITLE
Font pro Gotham pro nadpisy

### ISSUE THREAD

**Issue by janmichek** [keboola/indigo-ui#189]
Nasadily jsme samotny font Whitney do produkce (nebo se tak brzo stane). Pokracujeme tady:

Chceme do Produkce dostat i Font Gotham.
Uz jsme se to snazili protlacit, ale ve vysledku ty fonty byly vizualne matouci.
Nasazeni Whitney stabilizuje situaci ruznyho renderovani napric platformami.

Potom se podivame na nasledujici (netridene pididotazy a poznamky z predchozi issue)
- [ ] Nejdriv bych ty rezy odladil na Whitney a potom nahradil Gothamem
- [ ]  Gotham v nadpisech
- [ ]  Gotham v tlacitcich + akcnich odkazech
- [ ]  Gotham v GM (jen zde je Gotham 300)
- [ ]  Strukturovani formularu vs labels https://github.com/keboola/indigo-ui/issues/155
- [ ] Nazev entit?
- [ ] Upravit rezy Whitney na zaklade vyberu rezu Gotham
- [ ]  Navigace?
- [ ] Poresit kurzivu - vyhodit? dokumentovat? importovat rez?
- [ ] fonty vs Markup
- [ ] U mensich nadpisu je mozne dat Gotham 500... a co buttony?
- [ ] Nadpisy vzdy vetsi nez texty.
- [ ] Checknout jak dopadlo toto https://github.com/keboola/developer-portal-ui/issues/483
- [ ]  sjednotit nazvy entit v gridech - souvisi s https://github.com/keboola/kbc-ui/issues/1800 - muzem z toho neco zuzitkovat?
- [ ]  checknout souvisle upravy - https://github.com/keboola/kbc-ui/issues/1818
- [ ] checknout jestli muzeme neco zuzitkovat z predchozi vetve https://github.com/keboola/kbc-ui/commits/jan-new-fonts /// https://github.com/keboola/kbc-ui/pull/1688

**Comment by janmichek** [comment]
![image](https://user-images.githubusercontent.com/15363559/42512387-c7fa84f0-8454-11e8-914b-acede733e34d.png)

**Comment by janmichek** [comment]
Zaznamenal jsem i dalsi nazory ze font je zbytecne siroky oproti predchozim. Davam k diskuzi a ke zvazeni jestli nepouzit 'narrow' verzi fontu Whitney https://www.typography.com/fonts/whitney-narrow/overview/

![image](https://user-images.githubusercontent.com/15363559/42752201-7266d0aa-88ed-11e8-8ba6-167ee556f8b0.png)

**Comment by janmichek** [comment]
![image](https://user-images.githubusercontent.com/15363559/42752518-76ca9360-88ee-11e8-9fca-0c7a6dfcbb22.png)

**Comment by janmichek** [comment]
V tomto event logu mi to nejak taha oci. Tam by som skusil dat ten Narrow alebo Light. 
https://monosnap.com/file/bDnkw6Bd21skkO8CUMYmfvnBIhVK78

**Comment by janmichek** [comment]
https://github.com/keboola/kbc-ui/issues/1838

**Comment by janmichek** [comment]
https://github.com/keboola/indigo-ui/issues/213

**Comment by janmichek** [comment]
odpaddovat projekty / organizace
![image](https://user-images.githubusercontent.com/15363559/43524508-c983bea2-959f-11e8-98b3-1b0c553a8420.png)

**Comment by janmichek** [comment]
h2 vs h3  src/scripts/modules/components/react/pages/component-detail/ComponentDetail.coffee

**Comment by ujovlado** [comment]
Bude Roboto
